services:
  app:
    image: ghcr.io/financer-project/financer:latest
    container_name: financer-server
    environment:
      DATABASE_URL: mysql://root:password@financer-db:3306/financer
      REDIS_URL: redis://financer-redis:6379
      SESSION_SECRET_KEY:
    volumes:
      - ./data:/app/data
    ports:
      - "3000:3000"
    depends_on:
      mysql:
        condition: service_healthy
        restart: true
      redis:
        condition: service_started

  mysql:
    image: mysql:9
    container_name: financer-db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: financer
      MYSQL_USER: financer
      MYSQL_PASSWORD: password
    healthcheck:
      test: [ "CMD", "/usr/bin/mysql", "--user=root",  "--password=password", "--execute", "SHOW DATABASES;" ]
      interval: 10s
      timeout: 2s
      retries: 10
  #    volumes:
  #      - ./data:/var/lib/mysql

  redis:
    image: redis:alpine
    container_name: financer-redis
    ports:
      - 6379:6379
    volumes:
      - redis-data:/data
    command: redis-server --appendonly yes


volumes:
  redis-data:

networks:
  financer:
    external: true