services:
  mysql:
    image: mysql:9
    container_name: financer-db-test
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: financer-test
      MYSQL_USER: financer-test
      MYSQL_PASSWORD: password
    ports:
      - "3307:3306"
    healthcheck:
      test: [ "CMD", "/usr/bin/mysql", "--user=root",  "--password=password", "--execute", "SHOW DATABASES;" ]
      interval: 10s
      timeout: 2s
      retries: 10