import "./globals.css"
import { BlitzProvider } from "./blitz-client"
import { Inter } from "next/font/google"
import { Metadata } from "next"
import { cn } from "@/src/lib/util/utils"
import { Toaster } from "sonner"

const inter = Inter({ subsets: ["latin"] })

export const metadata: Metadata = {
    title: {
        default: "Financer",
        template: "%s – Financer"
    },
    description: "Generated by blitz new "
}

const themeScript = `
(function() {
  try {
    var match = document.cookie.match(/(?:^|;\\s*)financer-theme=([^;]*)/);
    var theme = match ? match[1] : 'light';
    var isDark = theme === 'dark' || (theme === 'system' && window.matchMedia('(prefers-color-scheme: dark)').matches);
    if (isDark) {
      document.documentElement.classList.add('dark');
    }
  } catch(e) {}
})()
`

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
    return (
        <html lang="en" suppressHydrationWarning>
        <body className={cn(inter.className)}>
        <script dangerouslySetInnerHTML={{ __html: themeScript }} />
        <BlitzProvider>
            <>{children}</>
            <Toaster />
        </BlitzProvider>
        </body>
        </html>
    )
}
