import "./globals.css"
import { BlitzProvider } from "./blitz-client"
import { Inter } from "next/font/google"
import { Metadata } from "next"
import { cn } from "@/src/lib/util/utils"
import { Toaster } from "sonner"

const inter = Inter({ subsets: ["latin"] })

export const metadata: Metadata = {
    title: {
        default: "Financer",
        template: "%s – Financer"
    },
    description: "Generated by blitz new "
}

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
    return (
        <html lang="en">
        <body className={cn(inter.className)}>
        <BlitzProvider>
            <>{children}</>
            <Toaster />
        </BlitzProvider>
        </body>
        </html>
    )
}
